Update to C11
Update build tooling to compile against C11.

After retargeting the Visual Studio solution to VS2022, the Windows
build begins failing with the following error:

```
gnulib\regex.h(650): error C2143: syntax error: missing ']' before 'restrict'
```

Upstream gnulib appears to contain an incomplete fix in commit
4cbc34fcd3 ("regex: Fix compilation error with MSVC 2022."). This error
may still need fixing in gnulib.

Fix this error with some small changes to gnulib/regex.h.

Signed-off-by: Brigham Campbell <me@brighamcampbell.com>