build: fix repoinfo.h dependency
The dependency of repoinfo.o with repoinfo.h was defined.
But the dependency of libctags_a-repoinfo.o with repoinfo.h was not defined.
As result "make tmain" following "configure" failed.

$ make distclean
...
$ ./autogen.sh
...
$ ./configure
...
$ make tmain
...
  CC       main/libctags_a-repoinfo.o
main/repoinfo.c:5:10: fatal error: main/repoinfo.h: No such file or directory
...